name: Psychosis
options:
  bundleIdPrefix: com.psychosis
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

targets:
  Psychosis:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Psychosis
    resources:
      - path: Psychosis/Resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.psychosis.app
      SWIFT_VERSION: "5.9"
      TARGETED_DEVICE_FAMILY: "1,2"
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      ENABLE_PREVIEWS: YES
      DEVELOPMENT_ASSET_PATHS: "Psychosis/Resources/Preview Content"

  PsychosisTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: PsychosisTests
    dependencies:
      - target: Psychosis
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.psychosis.app.tests
      SWIFT_VERSION: "5.9"
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Psychosis.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Psychosis"

schemes:
  Psychosis:
    build:
      targets:
        Psychosis: all
    test:
      targets:
        - PsychosisTests
    run:
      config: Debug

